default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: SM126723
  pool: 5

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  # основная база (primary)
  primary:
    url: <%= ENV["DATABASE_URL"] %>

  # база для ActionCable (solid_cable) — используем ту же самую
  cable:
    url: <%= ENV["DATABASE_URL"] %>
